### PR TITLE
PyO3, let's be able to import strop from python.

### PR DESCRIPTION
**Pull request by omarandlorraine**
This pull request logs the thoughts on using [PyO3](https://pyo3.rs/v0.16.4/) and maturin to create some kind of module that's importable from Python.

### CODE REVIEW

**Comment by omarandlorraine** [comment]
We need to figure out why the github action thing is not running on this PR.

**Comment by omarandlorraine** [comment]
works on my machine 🤷

**Comment by omarandlorraine** [comment]
Probably worth putting a cicd job & corresponding badge on the README.md to make sure any python files are properly linted. What shall we use, pylint?

**Comment by omarandlorraine** [comment]
Turns out PyO3 doesn't work nicely with rust Enums (fair enough; there is no real Python equivalent), I may redo Machine as a struct. This will affect all those match statements of course.

**Comment by LoganDark** [comment]
What's the utility of this? Do you plan on using *Python* for low-level compiling and binary stuff?

**Comment by LoganDark** [comment]
> > Could this be a separate, optional crate so if I want to use strop, I don't have to pull in Python stuff?
> 
> Uh, probably. I've heard of that kind of thing been done before, and it's a good idea. Can you figure it out?
> 
> One problem I know is I don't have a stable API yet.

Use a [cargo workspace](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) - store all crates in this one repository so that you can `cargo check` / `cargo test` across all members at once, and IDE refactoring also rewrites the references from other crates.

> And I also don't really know what it would look like yet.

I'd recommend a name like `strop-pyo3` that contains all the Python stuff, and just depends on `strop`. i.e. `strop` itself does not depend on Python or have any special APIs for only Python use.

This encourages you to design `strop`'s API in such a way that *anyone* can make their own crate like `strop-mlua` or `strop-qjs` or `strop-rhai` that bring `strop` bindings to other scripting languages.

**Comment by omarandlorraine** [comment]
Yeah I think what I'm doing here is the wrong approach. I'm just going to close this off.

**Comment by omarandlorraine** [comment]
LoganDark if we're forgetting about any kind of python frontend for this project, and having a separate crate instead, (and separate frontends for lisp, C, etc if we get around to it), then it also kind of makes sense to remove the JSON stuff as well. What do you think?

**Comment by LoganDark** [comment]
> LoganDark if we're forgetting about any kind of python frontend for this project, and having a separate crate instead, (and separate frontends for lisp, C, etc if we get around to it), then it also kind of makes sense to remove the JSON stuff as well. What do you think?

I think the JSON stuff can stay for the command-line binary, but yeah, in the core library you should just have generic stuff. i.e. pass a closure for tests

**Comment by omarandlorraine** [comment]
>pass a closure for tests

Okay. There appears to be a `variadic_closure` crate that looks promising.

**Comment by LoganDark** [comment]
> > pass a closure for tests
> 
> Okay. There appears to be a `variadic_closure` crate that looks promising.

What no. You don't need that... Why do you think you need that? You just have a closure that gets passed the generated program, and runs any tests on it - anything (equality, don't care bits, floating point etc...)

**Comment by omarandlorraine** [comment]
Oh, now I see which closure you mean! 

I was thinking that because the closure we're "compiling" can take any number of inputs and outputs, so I misunderstood what you meant.

**Comment by LoganDark** [comment]
> Oh, now I see which closure you mean!
> 
> I was thinking that because the closure we're "compiling" can take any number of inputs and outputs, so I misunderstood what you meant.

Sorry if my answer was rude/blunt, my keyboard is currently broken so I won't be able to offer much guidance/help for the next few weeks at least :/

**Pull request closed without merging**
